dist: xenial

language: c

# compilers to add to build matrix
compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libegl1-mesa-dev libgles2-mesa-dev

# scripts to run before build
before_script:
  - mkdir build
  - cd build
  - cmake ..

# build app, and run tests (ie make & make test)
script:
  - cmake --build .
  #- ctest --verbose
